import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { finalize } from 'rxjs';
import { AuthService } from '../../../core/services/auth.service';
import { GdFormControl, GdFormValue, Input } from '../../../shared/forms';
import { Button } from '../../../shared/ui';
@Component({selector:'gd-reset-password-page',imports:[ReactiveFormsModule,Input,Button],templateUrl:'./reset-password-page.html',changeDetection:ChangeDetectionStrategy.OnPush})
export class ResetPasswordPage { private readonly auth=inject(AuthService); private readonly router=inject(Router); protected readonly loading=signal(false); protected readonly token=signal<string|null>(null); protected readonly form=new FormGroup<{code:GdFormControl;password:GdFormControl;confirm:GdFormControl}>({code:new FormControl<GdFormValue>('',{validators:[Validators.required,Validators.pattern(/^\d{6}$/)]}),password:new FormControl<GdFormValue>('',{validators:[Validators.required,Validators.minLength(8)]}),confirm:new FormControl<GdFormValue>('',{validators:[Validators.required]})}); protected verify():void { if(this.form.controls.code.invalid){this.form.controls.code.markAsTouched();return;} this.loading.set(true); const email=history.state.email??''; this.auth.verifyPasswordRecoveryCode(email,`${this.form.controls.code.value}`).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>this.token.set(r.resetToken)}); } protected reset():void { const token=this.token(); if(!token||this.form.controls.password.value!==this.form.controls.confirm.value)return; this.loading.set(true);this.auth.resetPassword(token,`${this.form.controls.password.value}`,`${this.form.controls.confirm.value}`).pipe(finalize(()=>this.loading.set(false))).subscribe({next:()=>void this.router.navigate(['/login'])}); }}
